### ISSUE TITLE
Make SoundcraftUI IP address configurable in ui-testbed

### ISSUE THREAD

**Issue by 0b01001101** [fmalcher/soundcraft-ui#15]
It would be nice, if the SoundcraftUI IP address could be configured either by a config file or a cli flag.

**Comment by fmalcher** [comment]
Great point, thank you! If you have time, do you think you could file a PR?

**Comment by fmalcher** [comment]
Since the testbed application is a web app for the browser, it should be sensible to do the IP config via browser UI as well.
At the moment, the app automatically connects to the mixer on startup. We could build an extra express router for connection that can be fired from the UI with an input field.
