### ISSUE TITLE
Equalizer?

### ISSUE THREAD

**Issue by nicco2803** [fmalcher/soundcraft-ui#65]
Does anyone know how to work with EQ?

**Comment by fmalcher** [comment]
Equalizer control is not currently implemented in this library – but we *could* add it.
However, this is rather complicated since it's 3 parameters (freq, q, gain) that can be controlled independently. In the end it's just numeric values so no big deal.
I'd just implement this if it's really necessary, though.

**Comment by fmalcher** [comment]
You can actually send raw messages to the mixer:

```
const ui = new SoundcraftUi(ip);
// connect and wait …

ui.conn.sendMessage(message);
```

The EQ messages are structured like this:

```
SETD^i.5.eq.b1.freq^0.330531810826151
SETD^i.5.eq.b1.q^0.510485569690792
SETD^i.4.eq.b1.gain^0.5165745856353591
```

- `i.5`: Input 5
- `b1`: EQ Point 1
- value: between `0` and `1`. This range has to be transformed into the actual fader/frequency range!

**Comment by NaturalDevCR** [comment]
This would be soooo nice to have alongside with every other function from the mixer, so we could creat our own Ui... a nice to have... 

I have a question... what was the original purpose of this lib? because I would have believed that to create a custom Ui would it be.

Thanks for this work, I'll have so much fun with it.
